##service poty und projectname
server:
  port: 8081
  servlet:
    context-path: /notebook
##log notieren
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    level: error
  file:
    path: "./notelog"
    name: "./notelog/notebook.log"
    max-history: 10
##config front view
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/public/,classpath:/static/
##c3p0数据库配置
  datasource:
    c3p0:
      driverClass: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/cloud_note?useUnicode=true&characterEncoding=utf8& serverTimezone=UTC
      user: root
      password:
      initialPoolSize: 1
      maxPoolSize: 2
      minPoolSize: 1
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.proberen.www.entity
  configuration:
    map-underscore-to-camel-case: true
    database-id: datasource
