##service poty und projectname
server:
  port: 8081
  servlet:
    context-path: /notebook
##log notieren
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    level: debug
  file:
    path: "./notelog"
    name: "./notelog/notebook.log"
    max-history: 10
##config front view
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/public/,classpath:/static/
##c3p0数据库配置
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/cloud_note?useUnicode=true&characterEncoding=utf8& serverTimezone=UTC
    user: root
    password:
    initialPoolSize: 1
    minPoolSize: 1
    maxPoolSize: 2
    MaxIdleTime: 3000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 3000
      quiet-period: 1000

mybatis:
  mapper-locations: classpath:/mappers/CnUserMappper.xml
  type-aliases-package: com.proberen.www.entity
  configuration:
    map-underscore-to-camel-case: true

