##service poty und projectname
server:
  port: 8081
  servlet:
    context-path: /notebook
##log notieren
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    level: debug
  file:
    path: "./notelog"
    name: "./notelog/notebook.log"
    max-history: 10
##config front view
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/public/,classpath:/static/
##c3p0数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_note?useUnicode=true&characterEncoding=utf8& serverTimezone=UTC
    username: root
    password:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    initialPoolSize: 1
    min
    maxPoolSize: 2


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.proberen.www.entity
  configuration:
    map-underscore-to-camel-case: true

